### ISSUE TITLE
Allow for CloudApp links as well

### ISSUE THREAD

**Issue by cobbman** [d3fydev/asana-droplr-preview#5]
@amaterasher is it possible to allow this to work with our CloudApp links as well?

**Comment by arkinsons03** [comment]
I think, we can and since  cloudApp links area already in https, there's no need for us to redirect it to our backend. We can just render it directly in the chrome plugin.

**Comment by arkinsons03** [comment]
I am still finding another way on how to get the video without using CloudApp API.

**Comment by arkinsons03** [comment]
@bigwilliam Done with CloudApp support.  https://cl.ly/462b0M3A1s3v

**Comment by cobbman** [comment]
This looks really cool - excited to try it!
